- buildSrc/src/main/kotlin/P.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/MemberRole.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiMember.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiMemberImpl.kt
更新至simbot3.0.0.preview.1.1, 并根据版本调整更新相关API
> 更新至simbot3.0.0.preview.1.1

- buildSrc/src/main/kotlin/P.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiFriendEvents.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiFriendMessageEvent.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiGroupBotEvents.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiGroupMemberEvents.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiGroupMessageEvent.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiMemberMessageEvent.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiReceivedMessageContent.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiSimbotEvent.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/UnsupportedMiraiEvent.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiBotInvitedJoinGroupRequestEventImpl.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiFriendEventImpls.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiFriendMessageEventImpl.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiGroupBotEventImpls.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiGroupMemberEventImpls.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiGroupMessageEventImpl.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiGroupSettingEventImpls.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiInternalBotEventImpl.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiMemberMessageEventImpl.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiStrangerMessageEventImpl.kt
- core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiNudge.kt
- core/src/test/kotlin/BotTest.kt
根据pre.3.0调整API，移除所有Metadata相关内容
> 根据pre.3.0调整API

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiBotImpl.kt
相关事件类型：
- MiraiGroupNudgeEvent
- MiraiMemberNudgeEvent
- MiraiFriendNudgeEvent
- MiraiStrangerNudgeEvent
> 实现mirai戳一戳相关事件定义与推送

- simbot-component-mirai-boot/build.gradle.kts
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiBotManager.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiComponent.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiBotManagerImpl.kt
- simbot-component-mirai-core/src/test/kotlin/DeviceInfoTest.kt
根据simbot核心的 `v3.0.0.preview.8.0` 中的 `BotVerifyInfo` 重构内容进行相应调整。
> 跟进simbot核心更新： `BotVerifyInfo`

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiBot.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiContact.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiGroup.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiFriendImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiGroupImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiGroupMemberBotImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiMemberImpl.kt
> 根据新特性提供MiraiGroupMemberBot实现

- libs.versions.toml
- simbot-component-mirai-core/bot.config.json
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotVerifyInfoConfiguration.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiGroupSettingEvents.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiGroupSettingEventImpls.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiBotImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiMessageParser.kt
See mirai  [v2.12.1](https://github.com/mamoe/mirai/releases/tag/v2.12.1)
> 更新 `mirai-core` 版本到 v2.12.1

- buildSrc/src/main/kotlin/P.kt
- simbot-component-mirai-core/bot.config.json
- simbot-component-mirai-core/build.gradle.kts
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/SimpleDeviceInfo.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/DeviceInfoConfiguration.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotVerifyInfoConfiguration.kt
请参考 `love.forte.simbot.component.mirai.bot.DeviceInfoConfiguration.FileBased` 文档注释或 https://simbot.forte.love/docs/component-overview/mirai/bot-config
> 配置项 `deviceInfo` 支持类型 `file_based`

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiMember.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiMemberImpl.kt
- `isAnonymous`
- `muteTimeRemainingSeconds`
- `muteTimeRemaining` (for Kotlin)
- `muteTimeRemainingDuration`
- `isMuted`
> 为 `MiraiMember` 提供更多禁言和匿名相关的属性

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiMember.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiMemberImpl.kt
```kotlin
member.modifyAdmin(true)
member.appoint()
member.dismiss()
```
> 为 `MiraiMember` 提供管理员任免相关API

- buildSrc/src/main/kotlin/P.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiRecallMessageCacheStrategy.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/StandardMiraiRecallMessageCacheStrategyImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotVerifyInfoConfiguration.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/RecallMessageCacheStrategyConfiguration.kt
- simbot-component-mirai-core/src/test/kotlin/BotVerifyInfoConfigurationTest.kt
```json
{
"recallMessageCacheStrategyConfig": {
"type": "invalid"
}
}
```
> 为「缓存策略」提供新的配置形式 `recallMessageCacheStrategyConfig`

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBot.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiBotImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiFriendImpl.kt
```kotlin
val bot: MiraiBot = ...
val categories = bot.friendCategories
// ...
```
> 支持对bot好友分组列表的操作

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiComponent.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiComponentUsage.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotManagers.kt
例如 
```kotlin
val application = createSimpleApplication {
useMirai()
}
application.miraiBots { // MiraiBotManager
// ...
}
val botBotManager = application.firstMiraiBotManager
```
> 增加更多有关 Application 和 BotManagers 的扩展API

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/SimbotMiraiMessageReceiptImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiNudgeEvent.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiReceivedMessageContent.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiMessageChainContent.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiMessageContent.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/message/MiraiQuoteReply.kt
- simbot-component-mirai-extra-catcode/src/main/kotlin/love/forte/simbot/component/mirai/extra/catcode/CatCodeSerializer.kt
> 增加MessageSource的ID序列化方式；增加/改善MiraiQuoteReply的构建方式

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiGroupMemberEvents.kt
see https://github.com/simple-robot/simpler-robot/issues/573
> 改善事件实现。MiraiMemberLeaveEvent 现在实现 GroupMemberDecreaseEvent，MiraiMemberJoinEvent 现在实现 GroupMemberIncreaseEvent

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/SimbotMiraiMessageReceiptImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBot.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotManager.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotManagers.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotVerifyInfoConfiguration.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiGroupSettingEvents.kt
被标记的API会在正式版或RC版中被真正的物理删除，不会保留到正式版本中。
> 提升所有将会在正式版中移除的API的过时等级为ERROR

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBot.kt
**Kotlin**
```kotlin
val avatar: String = bot.avatar(AvatarSpec.LARGEST)
```
**Java**
```java
String avatar = bot.getAvatar(AvatarSpec.LARGEST);
```
> MiraiBot增加根据规格获取头像链接的API

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiFriend.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiMember.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiStranger.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiUserProfileQueryable.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBot.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiBotImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiFriendImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiGroupBotImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiMemberImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiStrangerImpl.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiUserProfileImpl.kt
> 部分类型支持查询 `MiraiUserProfile`

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/MiraiGroup.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiGroupImpl.kt
提供与mirai的 `GroupSettings` 相映射的封装类型来支持获取群设置信息。
```kotlin
val group: MiraiGroup = ...
val settings: MiraiGroupSettings = group.settings
```
> 支持获取**群设置**信息 via `MiraiGroup.settings`

- buildSrc/src/main/kotlin/P.kt
- simbot-component-mirai-core/build.gradle.kts
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiNudgeEvent.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiNudgeEventImpl.kt
see https://github.com/simple-robot/simpler-robot/issues/630
> 修复 `NudgeEvent.replyNudge` 无效的问题

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/MiraiNudgeEvent.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/event/impl/MiraiNudgeEventImpl.kt
> 改善 `NudgeEvent.replyNudge` 并增加更多相关API

- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotManager.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiBotManagerImpl.kt
增加 
```kotlin
register(Bot, MiraiBotConfiguration)
```
用来兼容未来可能出现的更多新的bot注册方式
> MiraiBotManager 增加注册函数

- simbot-component-mirai-core/bot.config.json
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/BotAuthorizationConfiguration.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotManager.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/MiraiBotVerifyInfoConfiguration.kt
- simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/PasswordInfoConfiguration.kt
- website/docs/bot-config.md
- website/static/schema/bot/0.3.0/bot.config.json
```json
{
"authorization": {
"type": "..."
}
}
```
旧的 `passwordInfo` 会暂做兼容并输出警告日志
> 使用新的配置项 `authorization` 替换 `passwordInfo`
